# Site settings
title: Nicola Blog
email: nicolar.bell@gmail.com
description: It's a test blog woo
baseurl: "/nicola-party"
twitter_username: nicolardesign
avatar: "https://pbs.twimg.com/profile_images/890479859079798784/IEYZDBwr_400x400.jpg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "My Author" # Set default author name
      categories: "cats"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

theme: jekyll-theme-slate